# Generated by Django 4.2.7 on 2023-11-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('ean', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=110)),
                ('quantity', models.IntegerField(max_length=110)),
            ],
        ),
    ]
