# Generated by Django 4.2.7 on 2023-11-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_products_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_created=True)),
                ('user_name', models.CharField(max_length=255)),
                ('products', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
