# Generated by Django 4.2.7 on 2023-11-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='route',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logs',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
