# Generated by Django 4.2.7 on 2023-11-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_logs_route_alter_logs_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
